---
title: "STAT 425 Final Project"
author: 'Jae-Ho Lee (UIN: 660868422, NetID: jlee571)'
date: "10/30/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```

```{r, load-library, warning = FALSE, message = FALSE}
library(readr)
library(purrr)
library(dplyr)
library(tidyr)
library(caret)
library(stringr)
library(ggplot2)
library(glmnet)
```

***

```{r, load-data, message = FALSE, warning = FALSE}
key = read_csv("key.csv")
test = read_csv("test.csv")
train = read_csv("train.csv")
weather = read_csv("weather.csv")
```

***

# preliminary data cleaning

```{r, merge-data}
# combind test-train set
data = bind_rows(train, test)

data = data %>% 
  left_join(key, by = c("store_nbr")) %>% 
  left_join(weather, by = c("station_nbr", "date"))
```

```{r, manipulate-data, warning = FALSE}
# subset and remove NAs
data = data %>% 
  as_tibble %>% 
  select(- depart) %>% 
  mutate_if(is.character, as.numeric)
  
# change item_nbr and store_nbr into categorical variables
data$item_nbr = factor(data$item_nbr)
data$store_nbr = factor(data$store_nbr)
data$station_nbr = factor(data$station_nbr)
```

```{r, test-train-split}
# split data into test-train 
train_index = 1:nrow(train)
test_index = (nrow(train) + 1):nrow(data)

mytrain = data[train_index, ] %>% select(-codesum)
mytest = data[test_index, ] %>% select(-codesum)
```

```{r, warning = FALSE}
# replace NA with median value
mytrain[6:21] = mytrain[6:12]%>% 
  map(~ replace_na(median(.x, na.rm=TRUE))) 
```

```{r}
map_dbl(mytrain, ~sum(is.na(.x)))
```

***

# Linear Regression Model / Diagnostics

```{r, sample-data}
set.seed(42)
random_samp = sample_n(mytrain, 5000)
```

```{r, build-model}
# linear model
lin_mod = lm(units ~ .  , data = mytrain)
```

```{r}
summary(lin_mod)
```

```{r, test, warning = FALSE}
predicted_lm = predict(lin_mod, mytest)
```

```{r, export-data}
# template = read_csv("sampleSubmission(1).csv")
# template$units = predicted_lm
# write.table(template, file = "submission1.csv", sep = ",", row.names = FALSE)
```

> The prediction results with the linear model received a Kaggle score of 0.93701.

***
```{r}
alias(lin_mod)
```

# Improvements

```{r}
x_mat = model.matrix(units ~ . , data = random_samp)

length(randamp$units)
nrow(mytrain)
ridge_mod = cv.glmnet(x_mat, random_samp$units, nfold = 5, alpha = 0)

```

```{r}
ridge = train(units ~ . , data = random_samp,
              method = 'ridge',
              trControl = trainControl(method = "cv", number = 5))
```

# Additional Data Manipulation

```{r, codesum-partition-function}
# function for extracting weather phenomena info from codesum
part = function(data, x) {
  str_detect(data, x)
}
```

```{r, further-manipulate-data}
# create dummy variables to replace codesum
var_codesum = data$codesum

data2 = data %>% 
  mutate(
    TS = part(var_codesum, 'TS'),
    GR = part(var_codesum, 'GR'),
    RA = part(var_codesum, 'RA'),
    DZ = part(var_codesum, 'DZ'),
    SN = part(var_codesum, 'SN'),
    SG = part(var_codesum, 'SG'),
    GS = part(var_codesum, 'GS'),
    PL = part(var_codesum, 'PL'),
    FG_plus = part(var_codesum, "FG\\+"),
    FG = part(var_codesum, 'FG'),
    BR = part(var_codesum, 'BR'),
    UP = part(var_codesum, 'UP'),
    HZ = part(var_codesum, 'HZ'),
    FU = part(var_codesum, 'FU'),
    DU = part(var_codesum, 'DU'),
    SS = part(var_codesum, 'SS'),
    SQ = part(var_codesum, 'SQ'),
    FZ = part(var_codesum, 'FZ'),
    MI = part(var_codesum, 'MI'),
    PR = part(var_codesum, 'PR'),
    BC = part(var_codesum, 'BC'),
    BL = part(var_codesum, 'BL'),
    VC = part(var_codesum, 'VC')
  ) %>% 
  select(- codesum) 

# replace NA with median value
data2[6:21] = data2[6:21] %>% 
  map(~ replace_na(median(.x, na.rm=TRUE))) 

# replace NA in (codesome) dummy variables with FALSE
data2[22:44] = data2[22:44] %>% 
  map(~ replace_na(FALSE)) 
```

```{r, second-test-train-split}
# split data into test-train 
train_index = 1:nrow(train)
test_index = (nrow(train) + 1):nrow(data)

train2 = data2[train_index, ] 
test2 = data2[test_index, ]
```
